
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '$\x14\rM\xf4\xa1]\xfd\xeb5-\xcd\x03#\x8d['
    
_lr_action_items = {'DEDENT':([10,12,13,14,15,16,],[-1,-6,16,-8,-7,-5,]),'INDENT':([9,],[11,]),'STRING':([6,11,],[8,12,]),'NAME':([0,2,11,],[2,3,2,]),'NEWLINE':([7,],[9,]),'$end':([1,10,16,],[0,-1,-5,]),'OP':([2,3,4,5,8,],[-3,6,7,-2,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'attr':([2,],[5,]),'stmts':([11,],[13,]),'stmt':([11,],[14,]),'tag':([0,11,],[1,15,]),'attrs':([2,],[4,]),'suite':([7,],[10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tag","S'",1,None,None,None),
  ('tag -> NAME attrs OP suite','tag',4,'p_TAG','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',72),
  ('attrs -> attr','attrs',1,'p_attrs','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',76),
  ('attrs -> <empty>','attrs',0,'p_attrs','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',77),
  ('attr -> NAME OP STRING','attr',3,'p_attr','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',81),
  ('suite -> NEWLINE INDENT stmts DEDENT','suite',4,'p_suite','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',85),
  ('stmt -> STRING','stmt',1,'p_statement','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',89),
  ('stmt -> tag','stmt',1,'p_statement','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',90),
  ('stmts -> stmt','stmts',1,'p_multi_statements','C:\\Users\\karuna\\Desktop\\Jython\\Python\\My Modules\\PYTML\\PYTML\\DEV\\tokenizer.py',94),
]
